# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=acceptance_tests (25)
      - check-success=acceptance_tests (28)
      - check-success=acceptance_tests (29)
    actions:
      merge:
        method: squash

  - name: Be author's friend
    conditions:
      - author~=^ubiratansoares
      - check-success=acceptance_tests (25)
      - check-success=acceptance_tests (28)
      - check-success=acceptance_tests (29)
    actions:
      merge:
        method: squash